### ISSUE TITLE
Question for the tooling system.

### ISSUE THREAD

**Issue by zorone** [MrPatchara/Assembly-subject#1]
สวัสดีครับ ผมอิมรอนนะครับ เรียนวิศวะคอมรามเนี่ยแหละครับ อยู่ปี 3 sec. 1 คือเผอิญว่าผมเห็นโปรแกรมชื่อ Assembly Opcode Finder (MCS-51) อยู่บนเครื่องคอมที่คณะน่ะครับ (พอดีเป็นที่นั่งประจำของผมพอดีด้วยแหละครับ เปิดคอมขึ้นมาเลยเห็น)

เรื่องของเรื่องคือ โปรแกรมนี้พี่เป็นคนเขียนเองหรือเปล่าครับ ผมหาวิธีติดตั้งโปรแกรมนี้อยู่ เห็นว่าน่าสนใจดีน่ะครับ

ที่ผมเจอพี่ได้ เพราะดูจากเมนู help ในโปรแกรมน่ะครับ แล้วเจอลิงก์ github พี่ เลยตามลิงก์มาเผื่อจะเจอวิธีติดตั้งน่ะครับ คิดว่า repos นี้น่าจะตรงสุด แต่ก็ยังหาวิธีติดตั้งไม่เจออยู่ดีครับ

เท่าที่ผมแกะข้อมูลมา พี่น่าจะเอาโปรแกรมมาจาก [https://edsim51.com/](https://edsim51.com/) ใช่ไหมครับ แล้วพี่เขียน Java ไว้เบื้องหน้าเอา ผมแปลกใจมากที่ใน project มีทั้งตัว uninstaller ทั้ง library ของ python (ซึ่งไม่ควรมี) ผมเลยอยากทราบว่าพี่เขียนเติมขึ้นมายังไงน่ะครับ ที่ผมสับสน เพราะผมเองก็กำลังเรียนวิชา software engineering ซึ่งมีให้ทำเกี่ยวกับหน้า GUI บน java ด้วย แต่หน้าตา element UI เป็นคนละแบบกับที่ผมเรียนอยู่เลย เลยสงสัยครับ

อ้อ คือผมเรียนวิชาสถาปัตยกรรมคอมพิวเตอร์ของอาจารย์สุรพงษ์อยู่ด้วยน่ะครับ ที่ผมสนใจโปรแกรมนี้เพราะแบบนี้นั่นแหละครับ

ในกรณีของผมนะ ผมใช้โปรแกรม dosbox-x เอา แล้วเรียกโปรแกรม monica51 ที่ให้มากับแผ่น CD เอาน่ะครับ ต่อ port serial ได้ด้วย ใช้งานกับตัวเครื่อง ET-board V6 ได้สบายเลย แต่ผมคงลืมตั้งค่าลงคอมพิวเตอร์ให้มั้ง เดี๋ยวผมตั้งค่าให้

อื้อ อีกเรื่องครับ พี่น่าจะเรียน sec. 3 ใช่ไหมครับ วิชานี้ (CPE3427) อาจารย์สุรพงษ์ปิดคอร์สไปแล้วยังครับ คือเผื่อผมจะมีโอกาสมาเจอ และคุยกับพี่ซักหน่อยน่ะครับ

ผมขอขอบคุณสำหรับคำตอบล่วงหน้านะครับ

ด้วยความเคารพ
อิมรอน

**Comment by MrPatchara** [comment]
สวัสดีครับ ใช่ครับ โปรแกรมพี่เอง พอดีเป็นวิชาเรียน แอสเซมบลี พี่เลยทําโปนแกรมขําๆ ไว้ช่วยเรียนครับ ส่วนการ install พี่ทำเป็น .exe ก่อน แล้วทำตัว install ครับ ส่วนวิชาเรียนพี่เพิ่งปิดคอร์สไปครับ เหลือแต่สอบแล้ว ยังไงแอดไลน์ มาตุยกันได้นะครับ line id :rbangnat

**Comment by zorone** [comment]
ได้ครับพี่ เดี๋ยวผมแอดไปนะ
